services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASS}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data #Los datos se guardan
volumes:
  postgres_data:
